services:
  ### Web Server Container
  web:
    image: lobsterk/web-nginx-php
    container_name: web-financeM
    restart: always
    ports:
      - "8179:80"
    volumes:
      - ./:/var/www/
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/php-fpm/php.ini:/etc/php/7.4/fpm/php.ini
      - ./.docker/php-fpm/php-fpm.conf:/etc/php/7.4/fpm/php-fpm.conf

  ## MySQL Container
  mysql:
    image: mysql:8.0
    container_name: mysqlfinanceM
    restart: always
    ports:
      - "3301:3306"  # Исправлено на 3306, так как MySQL по умолчанию использует этот порт.
    environment:
      MYSQL_DATABASE: dbtest
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: r1234

  ## Adminer container
  adminer:
    image: adminer
    container_name: adminerfinanceM
    depends_on:
      - mysql  # Зависимость от mysql сервиса
    ports:
      - "8089:8080"  # Исправлено на 8080, так как Adminer по умолчанию использует этот порт.

  ## Redis Container
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_PASSWORD=my_master_password
    ports:
      - '6372:6379'